name: Build and Release

on:
  push:
    branches:
      - main  # 适应你的主分支

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的Ubuntu环境，可以根据需要更改

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v4.0.0
      with:
        distribution: 'adopt'
        java-version: '8'  # 使用Java 8，根据你的要求更改

    - name: Checkout Repository
      uses: actions/checkout@v4.0.0

    - name: Install Dependencies
      run: |
       sudo apt install apktool signapk openjdk-8-jdk
       sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac

    - name: Compile Java Classes
      run: |
        cd mybv/java
        ./build.sh
        cd ../..
    
    - name: List Current Directioy
      run: Is    

    - name: Build APK
      run: ./build.sh
